apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
data:
  S3_DATA_KEY: {{ .Values.s3.dataKey | quote }}
  S3_STATE_KEY: {{ .Values.s3.stateKey | quote }}
  S3_ENDPOINT_URL: {{ .Values.s3.endpoint | quote }}
  S3_BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  DATA_DIR_PATH: {{ .Values.geoserverDataDir | quote }}
  UPDATE_INTERVAL: {{ .Values.updateInterval | default 120000 | quote }}