apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "geoserver.fullname" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "geoserver.fullname" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      name: {{ template "geoserver.fullname" . }}
      labels:
        app: {{ template "geoserver.fullname" . }}
        chart: {{ template "geoserver.chart" . }}
        release: {{ .Release.Name | quote }}
        {{- with .Values.podLabels }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- (tpl . $) | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: {{ template "geoserver.fullname" . }}-init
          image: {{ template "geoserver.sidecarImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: IS_INIT_MODE
              value: 'true'
          envFrom:
            - secretRef:
                name: {{ template "geoserver.secretName" . }}
            - configMapRef:
                name: {{ template "geoserver.fullname" . }}
          volumeMounts:
          - mountPath: {{ .Values.geoserverDataDir }}
            name: data-dir-volume
      containers:
        - name: {{ template "geoserver.fullname" . }}
          image: {{ template "geoserver.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.geoserverDataDir }}
            - name: GEOSERVER_DATA_DIR
              value: {{ .Values.geoserverDataDir | quote }}
            {{- end }}
            - name: GEOSERVER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: GEOSERVER_USER
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: GEOSERVER_PASS
            {{- with .Values.extraGeoserverEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http-geoserver
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /geoserver
              port: http-geoserver
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /geoserver
              port: http-geoserver
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /geoserver
              port: http-geoserver
              scheme: HTTP
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          volumeMounts:
          - mountPath: {{ .Values.geoserverDataDir }}
            name: data-dir-volume
        - name: {{ template "geoserver.fullname" . }}-config
          image: {{ template "geoserver.sidecarImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.sidecarResources | nindent 12 }}
          {{- end }}
          env:
            - name: IS_INIT_MODE
              value: 'false'
            - name: GEOSERVER_URL
              value: http://localhost:8080/geoserver/rest/reload
            {{- with .Values.extraSidecarEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "geoserver.secretName" . }}
            - configMapRef:
                name: {{ template "geoserver.fullname" . }}
          volumeMounts:
          - mountPath: {{ .Values.geoserverDataDir }}
            name: data-dir-volume
      volumes:
      - name: data-dir-volume
        emptyDir: {}

