apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geoserver.secretName" . }}
  labels:
    app: {{ template "geoserver.fullname" . }}
    chart: {{ template "geoserver.chart" . }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  GEOSERVER_USER: {{ .Values.geoserverUser | b64enc | quote }}
  GEOSERVER_PASS: {{ .Values.geoserverPassword | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey | b64enc | quote }}
